
AllCops:
  Exclude:
    - bin/**
    - db/**/*
    - vendor/**/*

AbcSize:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
